
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 68;
  public static final int NUMERO = 59;
  public static final int CONS = 55;
  public static final int DOSPUNTOS = 51;
  public static final int MASMAS = 7;
  public static final int THE = 50;
  public static final int MAYORRIGUAL = 19;
  public static final int MENOSMENOS = 8;
  public static final int CHARR = 32;
  public static final int POR = 28;
  public static final int RET = 42;
  public static final int MENORR = 16;
  public static final int MASS = 58;
  public static final int STRINGG = 36;
  public static final int FINA = 41;
  public static final int CAS = 47;
  public static final int DIFERENTE = 20;
  public static final int MENORRIGUAL = 17;
  public static final int INT = 31;
  public static final int PUNTOCOMA = 14;
  public static final int ORR = 23;
  public static final int STAT = 40;
  public static final int SWIT = 52;
  public static final int PUB = 37;
  public static final int IGUAL = 64;
  public static final int ELS = 45;
  public static final int PROTEC = 38;
  public static final int DOUB = 34;
  public static final int READL = 56;
  public static final int BOOL = 33;
  public static final int WRITEL = 57;
  public static final int COMILLASIMP = 29;
  public static final int EOF = 0;
  public static final int DOO = 53;
  public static final int VOIDD = 3;
  public static final int error = 1;
  public static final int COMILLA = 5;
  public static final int COMA = 13;
  public static final int MODULO = 26;
  public static final int MENOS = 27;
  public static final int TEXTO1 = 67;
  public static final int IMP = 2;
  public static final int NOTT = 24;
  public static final int PAR_B = 10;
  public static final int GUALIGUAL = 21;
  public static final int PAR_A = 9;
  public static final int TRU = 65;
  public static final int PRIV = 39;
  public static final int CLAS = 4;
  public static final int IDD = 60;
  public static final int PACK = 54;
  public static final int LONGG = 35;
  public static final int NEWW = 6;
  public static final int MAYORR = 18;
  public static final int PUNTO = 15;
  public static final int DIVIDIR = 30;
  public static final int ANDD = 22;
  public static final int IGUALIGUAL = 62;
  public static final int WHIL = 49;
  public static final int FILA = 61;
  public static final int CORRCH_B = 12;
  public static final int CORRCH_A = 11;
  public static final int DEF = 46;
  public static final int BRE = 43;
  public static final int FAL = 66;
  public static final int TEXTO = 63;
  public static final int FORR = 48;
  public static final int IFF = 44;
  public static final int MAS = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IMP",
  "VOIDD",
  "CLAS",
  "COMILLA",
  "NEWW",
  "MASMAS",
  "MENOSMENOS",
  "PAR_A",
  "PAR_B",
  "CORRCH_A",
  "CORRCH_B",
  "COMA",
  "PUNTOCOMA",
  "PUNTO",
  "MENORR",
  "MENORRIGUAL",
  "MAYORR",
  "MAYORRIGUAL",
  "DIFERENTE",
  "GUALIGUAL",
  "ANDD",
  "ORR",
  "NOTT",
  "MAS",
  "MODULO",
  "MENOS",
  "POR",
  "COMILLASIMP",
  "DIVIDIR",
  "INT",
  "CHARR",
  "BOOL",
  "DOUB",
  "LONGG",
  "STRINGG",
  "PUB",
  "PROTEC",
  "PRIV",
  "STAT",
  "FINA",
  "RET",
  "BRE",
  "IFF",
  "ELS",
  "DEF",
  "CAS",
  "FORR",
  "WHIL",
  "THE",
  "DOSPUNTOS",
  "SWIT",
  "DOO",
  "PACK",
  "CONS",
  "READL",
  "WRITEL",
  "MASS",
  "NUMERO",
  "IDD",
  "FILA",
  "IGUALIGUAL",
  "TEXTO",
  "IGUAL",
  "TRU",
  "FAL",
  "TEXTO1",
  "CONT"
  };
}

